# Generated by Django 6.1 on 2026-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ('id',), 'verbose_name': 'Proxy', 'verbose_name_plural': 'Proxies'},
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Proxy password'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Proxy username'),
        ),
    ]
