# Generated by Django 6.1 on 2026-08-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workergroup_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Online/offline'),
            preserve_default=False,
        ),
    ]
