# Generated by Django 6.1 on 2026-09-22 08:49

from django.db import migrations
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from core import utils

DEFAULT_USERNAME = 'admin'
DEFAULT_PASSWORD = 'simple-split-proxy-password'
DEFAULT_PROXY_USERNAME = 'test-proxy'
DEFAULT_PROXY_PASSWORD = 'test-proxy-password'


def create_initial_data(apps, schema_editor):
    User = get_user_model()
    profile = User.objects.create(username=DEFAULT_USERNAME, is_superuser=True)
    profile.set_password(DEFAULT_PASSWORD)
    profile.save()
    Proxy = apps.get_model("core", "Proxy")
    Proxy.objects.create(username=DEFAULT_PROXY_USERNAME, password=make_password(DEFAULT_PROXY_PASSWORD))
    utils.rds.set(settings.DEFAULT_ROUTE_REDIS_KEY, settings.DEFAULT_GROUP_NAME)


def remove_initial_data(apps, schema_editor):
    User = get_user_model()
    Proxy = apps.get_model("core", "Proxy")
    User.objects.filter(username=DEFAULT_USERNAME).delete()
    Proxy.objects.filter(username=DEFAULT_PROXY_USERNAME).delete()
    utils.rds.delete(settings.DEFAULT_ROUTE_REDIS_KEY)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_online'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, remove_initial_data),
    ]
