[pytest]
python_files = tests/*.py
DJANGO_SETTINGS_MODULE = main.settings
addopts =
#  --cov
#  --reuse-db
#  --nomigrations
filterwarnings =
  ignore:builtin type (SwigPyPacked|SwigPyObject|swigvarlink) has no __module__ attribute:DeprecationWarning
  ignore::RuntimeWarning
env =
  DEBUG=true
  DJANGO_SECRET_KEY='123'
  TESTING=true
  DJANGO_ALLOWED_HOSTS='*'
  DEFAULT_GROUP_NAME='direct'
  DOMAINS_REDIS_KEY="routes:domains"
  CIDRS_REDIS_KEY="routes:cidr"
  DEFAULT_ROUTE_REDIS_KEY="routes:default"
  REDIS_HOST=redis_test
  REDIS_PORT=6379
  REDIS_DB=10
  REDIS_PASSWORD=some-secret
